//translate_point_e_3d(x,y,z,direction,pitch);
var _x, _y, _z, _dir, _pit, _rot, _dist, _tdir, _result, _fx, _fy, _fz, _xydir, _xzdir;
_x = argument0;
_y = argument1;
_z = argument2;
_dir = argument3;
_pit = argument4;
//_rot = argument5;
_fx = 0;
_fy = 0;
_fz = 0;

_dist = point_distance_3d(0,0,0,_x,_y,_z);
//_dist = point_distance(0,0,_x,_y);
_xydir = point_direction(0,0,_x,_y) + _dir;
_xzdir = point_direction(0,0,_z,_x) + _pit;
//_xzdir = 0;
_result[0] = d3d_lengthdir_x(_dist,_xydir,_xzdir);
_result[1] = d3d_lengthdir_y(_dist,_xydir,_xzdir);
_result[2] = _z//d3d_lengthdir_z(_dist,_xydir,_xzdir);
return _result;
